# This is a basic workflow to help you get started with Actions

name: DTC

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ubuntu18_04-gcc4_8:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 4.8
      
      - name: install dependency
        run: |
          sudo apt-get install -y make zlib1g zlib1g-dev bzip2 liblz4-dev libasan0 openssl libmxml-dev

      # Runs a set of commands using the runners shell
      - name: cmake project
        run: |
          cd ${{github.workspace}}
          mkdir build
          cd build
          cmake ../
          make
          
  ubuntu18_04-gcc5:
      # The type of runner that the job will run on
      runs-on: ubuntu-18.04

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        - name: Install GCC
          uses: egor-tensin/setup-gcc@v1
          with:
            version: 5

        - name: install dependency
          run: |
            sudo apt-get install -y make zlib1g zlib1g-dev bzip2 liblz4-dev libasan0 openssl libmxml-dev

        # Runs a set of commands using the runners shell
        - name: cmake project
          run: |
            cd ${{github.workspace}}
            mkdir build
            cd build
            cmake ../
            make
